import { useSiteReducedMotion } from '../motion/MotionProvider';
import { ArrowLeft, ArrowRight, Check, Edit3, Search } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { demoPixRecipients, pixRecipientExamples } from '../data/pixRecipients';
import { formatDateTime, formatMoney } from '../domain/formatters';
import type { PixRecipient, Transaction } from '../domain/models';
import { detectPixKeyType, findPixRecipient, validatePixAmount } from '../domain/pix';
import { useFinancialStore } from '../state/financialStore';
import { AppHeader } from '../ui/AppHeader';
import { BalanceReaction } from '../ui/BalanceReaction';
import { PixFlow } from '../ui/PixFlow';
import { Receipt } from '../ui/Receipt';

type PixStep = 'recipient' | 'amount' | 'review' | 'reaction' | 'receipt';
const stepIndex: Record<PixStep, number> = { recipient: 0, amount: 1, review: 2, reaction: 3, receipt: 4 };
const parseMoneyInput = (value: string) => Number(value.replace(/\D/g, '')) / 100;

export function PixRoute() {
  const reducedMotion = useSiteReducedMotion();
  const snapshot = useFinancialStore();
  const [step, setStep] = useState<PixStep>('recipient');
  const [keyValue, setKeyValue] = useState('');
  const [recipient, setRecipient] = useState<PixRecipient | null>(null);
  const [amount, setAmount] = useState(0);
  const [amountText, setAmountText] = useState('');
  const [error, setError] = useState('');
  const [processing, setProcessing] = useState(false);
  const [transaction, setTransaction] = useState<Transaction | null>(null);
  const [operationId, setOperationId] = useState(() => crypto.randomUUID());
  const confirmLock = useRef(false);
  const reactionTimer = useRef<number | null>(null);
  const unread = snapshot.notifications.filter((item) => !item.read).length;
  const afterBalance = Math.max(0, snapshot.balance.available - amount);
  useEffect(() => {
    document.querySelector<HTMLElement>(`[data-pix-step-title="${step}"]`)?.focus({ preventScroll: true });
  }, [step]);
  useEffect(() => () => { if (reactionTimer.current !== null) window.clearTimeout(reactionTimer.current); }, []);
  const recipientStatus = useMemo(() => { if (!keyValue.trim()) return null; const type = detectPixKeyType(keyValue); if (!type) return { kind: 'invalid' as const, message: 'A chave não tem um formato Pix válido.' }; const found = findPixRecipient(keyValue, demoPixRecipients); if (!found) return { kind: 'not-found' as const, message: 'Não encontramos um destinatário para esta chave.' }; return { kind: 'found' as const, recipient: found }; }, [keyValue]);
  const chooseRecipient = (event: FormEvent) => { event.preventDefault(); if (!recipientStatus || recipientStatus.kind !== 'found') { setError(recipientStatus?.message ?? 'Informe uma chave Pix.'); requestAnimationFrame(() => document.getElementById('pix-key')?.focus()); return; } setRecipient(recipientStatus.recipient); setError(''); setStep('amount'); };
  const chooseAmount = (event: FormEvent) => { event.preventDefault(); const validation = validatePixAmount(amount, snapshot); if (validation && !validation.ok) { setError(validation.message); requestAnimationFrame(() => document.getElementById('pix-amount')?.focus()); return; } setError(''); setStep('review'); };
  const confirmPix = () => { if (!recipient || processing || confirmLock.current) return; confirmLock.current = true; setProcessing(true); const result = snapshot.submitPix({ operationId, recipient, amount, createdAt: new Date().toISOString() }); if (!result.ok) { setError(result.message); setProcessing(false); confirmLock.current = false; return; } setTransaction(result.transaction); setStep('reaction'); const duration = reducedMotion ? 0 : 1180; reactionTimer.current = window.setTimeout(() => { setStep('receipt'); setProcessing(false); reactionTimer.current = null; }, duration); };
  const startAnother = () => { if (reactionTimer.current !== null) window.clearTimeout(reactionTimer.current); reactionTimer.current = null; setKeyValue(''); setRecipient(null); setAmount(0); setAmountText(''); setError(''); setTransaction(null); setOperationId(crypto.randomUUID()); confirmLock.current = false; setStep('recipient'); };
  const datePreview = formatDateTime(new Date().toISOString());
  const recipientFeedback = error || (recipientStatus && recipientStatus.kind !== 'found' ? recipientStatus.message : '');
  return <div className="pix-page vertical-slice mineral-scene route-stage" data-flow-step={step}><div className="mineral-backdrop" aria-hidden="true" /><div className="mineral-atmosphere" aria-hidden="true" /><a className="skip-link" href="#pix-content">Pular para o Pix</a><AppHeader unreadCount={unread} showAccent /><main className="pix-shell" id="pix-content"><header className="pix-header"><Link to="/dashboard" className="back-link" viewTransition><ArrowLeft aria-hidden="true" /> Dashboard</Link><div><p className="kicker">PIX / DINHEIRO EM MOVIMENTO</p><h1 tabIndex={-1} data-pix-step-title={step === 'receipt' ? 'receipt' : undefined}>{step === 'receipt' ? 'Comprovante' : 'Mover dinheiro.'}</h1></div><PixFlow active={stepIndex[step]} /></header>
  {recipient && step !== 'recipient' && <aside className="pix-continuity" aria-label="Contexto do Pix em andamento"><span><small>ORIGEM</small><strong>{snapshot.account.institution}</strong></span><i aria-hidden="true" /><span><small>DESTINO</small><strong>{recipient.name}</strong></span><i aria-hidden="true" /><span className="pix-continuity__amount"><small>VALOR</small><strong>{amount ? formatMoney(amount) : 'A definir'}</strong></span></aside>}
  {step === 'recipient' && <section className="pix-stage pix-stage--recipient" aria-labelledby="recipient-title"><div className="pix-stage__context"><span>01</span><p>ORIGEM → DESTINO</p><h2 id="recipient-title" tabIndex={-1} data-pix-step-title="recipient">Para quem<br />você envia?</h2><p>Informe uma chave. O destinatário precisa ser reconhecido antes de qualquer valor.</p></div><form className="pix-form pix-surface" onSubmit={chooseRecipient} noValidate><label htmlFor="pix-key">Chave Pix</label><div className="pix-key-input"><Search aria-hidden="true" /><input id="pix-key" value={keyValue} onChange={(event) => { setKeyValue(event.target.value); setError(''); }} placeholder="CPF, telefone, e-mail ou chave aleatória" autoComplete="off" aria-invalid={Boolean(error)} aria-describedby={recipientFeedback ? 'pix-key-help pix-error' : 'pix-key-help'} /></div><p id="pix-key-help" className="pix-help">Exemplo: <button type="button" onClick={() => setKeyValue(pixRecipientExamples.email)}>{pixRecipientExamples.email}</button></p>{recipientStatus?.kind === 'found' && <div className="recipient-result" aria-live="polite"><span><Check aria-hidden="true" /></span><div><strong>{recipientStatus.recipient.name}</strong><small>{recipientStatus.recipient.maskedKey}</small><small>{recipientStatus.recipient.institution} · {recipientStatus.recipient.taxIdSuffix}</small></div></div>}{recipientFeedback && <p id="pix-error" className="field__error" role={error ? 'alert' : undefined} aria-live={error ? undefined : 'polite'}>{recipientFeedback}</p>}<button className="ngb-button ngb-button--primary pix-primary" type="submit">Continuar <ArrowRight aria-hidden="true" /></button></form></section>}
  {step === 'amount' && recipient && <section className="pix-stage pix-stage--amount" aria-labelledby="amount-title"><div className="pix-stage__context"><span>02</span><p>VALOR E SALDO</p><h2 id="amount-title" tabIndex={-1} data-pix-step-title="amount">Quanto vai<br />se mover?</h2><div className="recipient-inline"><strong>{recipient.name}</strong><span>{recipient.maskedKey}</span><button type="button" onClick={() => setStep('recipient')}><Edit3 aria-hidden="true" /> Alterar</button></div></div><form className="amount-form pix-surface" onSubmit={chooseAmount} noValidate><label htmlFor="pix-amount">Valor do Pix</label><div className="amount-input"><span>R$</span><input id="pix-amount" inputMode="numeric" value={amountText} onChange={(event) => { const next = parseMoneyInput(event.target.value); setAmount(next); setAmountText(next ? next.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : ''); setError(''); }} placeholder="0,00" aria-invalid={Boolean(error)} aria-describedby={error ? 'amount-error' : undefined} /></div><div className="choice-split" aria-live="polite"><div><span>SALDO ATUAL</span><strong>{formatMoney(snapshot.balance.available)}</strong></div><div className="choice-split__send"><span>ENVIAR</span><strong>− {formatMoney(amount)}</strong></div><div><span>MANTER DISPONÍVEL</span><strong>{formatMoney(afterBalance)}</strong></div></div><p className="pix-limit">Limite Pix diário: {formatMoney(snapshot.account.pixDailyLimit)}</p>{error && <p id="amount-error" className="field__error" role="alert">{error}</p>}<button className="ngb-button ngb-button--primary pix-primary" type="submit">Revisar Pix <ArrowRight aria-hidden="true" /></button></form></section>}
  {step === 'review' && recipient && <section className="pix-stage pix-stage--review" aria-labelledby="review-title"><div className="pix-stage__context"><span>03</span><p>DECISÃO</p><h2 id="review-title" tabIndex={-1} data-pix-step-title="review">Revise antes<br />de confirmar.</h2><p>O saldo só será alterado depois da sua confirmação.</p></div><div className="pix-review pix-surface"><p className="pix-review__amount">{formatMoney(amount)}</p><dl><div><dt>Origem</dt><dd>{snapshot.account.institution}<small>Ag. {snapshot.account.branch} · Conta {snapshot.account.number}</small></dd></div><div><dt>Destinatário</dt><dd>{recipient.name}<small>{recipient.taxIdSuffix}</small></dd></div><div><dt>Chave</dt><dd>{recipient.maskedKey}</dd></div><div><dt>Instituição</dt><dd>{recipient.institution}</dd></div><div><dt>Data</dt><dd>{datePreview.date}, agora</dd></div><div><dt>Saldo após o Pix</dt><dd>{formatMoney(afterBalance)}</dd></div></dl>{error && <p className="field__error" role="alert">{error}</p>}<div className="pix-review__actions"><button type="button" onClick={() => setStep('amount')} disabled={processing}>Voltar e editar</button><button className="ngb-button ngb-button--primary pix-confirm" type="button" onClick={confirmPix} disabled={processing}>{processing ? 'Confirmando…' : `Confirmar Pix de ${formatMoney(amount)}`} <ArrowRight aria-hidden="true" /></button></div></div></section>}
  {step === 'reaction' && transaction && <BalanceReaction amount={transaction.amount} direction="out" previousBalance={snapshot.balance.available + transaction.amount} currentBalance={snapshot.balance.available} detail={`para ${transaction.recipient}`} statusLabel="Pix confirmado" titleId="reaction-title" focusAttribute="data-pix-step-title" />}
  {step === 'receipt' && transaction && <section className="receipt-stage"><Receipt transaction={transaction} headingLevel="h2" /><div className="receipt-next"><Link className="ngb-button ngb-button--primary" to="/dashboard" state={{ dashboardFocus: 'capital', transactionId: transaction.id }} viewTransition>Voltar ao Dashboard <ArrowRight aria-hidden="true" /></Link><button className="ngb-button ngb-button--secondary" type="button" onClick={startAnother}>Fazer outro Pix</button></div></section>}</main></div>;
}
