import { ArrowLeft, ArrowRight, Check, Edit3, Search } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { demoPixRecipients, pixRecipientExamples } from '../data/pixRecipients';
import { formatDateTime, formatMoney } from '../domain/formatters';
import type { PixRecipient, Transaction } from '../domain/models';
import { detectPixKeyType, findPixRecipient, validatePixAmount } from '../domain/pix';
import { useFinancialStore } from '../state/financialStore';
import { AppHeader } from '../ui/AppHeader';
import { PixFlow } from '../ui/PixFlow';
import { Receipt } from '../ui/Receipt';

type PixStep = 'recipient' | 'amount' | 'review' | 'reaction' | 'receipt';
const stepIndex: Record<PixStep, number> = { recipient: 0, amount: 1, review: 1, reaction: 2, receipt: 3 };
const parseMoneyInput = (value: string) => Number(value.replace(/\D/g, '')) / 100;

export function PixRoute() {
  const snapshot = useFinancialStore();
  const [step, setStep] = useState<PixStep>('recipient');
  const [keyValue, setKeyValue] = useState('');
  const [recipient, setRecipient] = useState<PixRecipient | null>(null);
  const [amount, setAmount] = useState(0);
  const [amountText, setAmountText] = useState('');
  const [error, setError] = useState('');
  const [processing, setProcessing] = useState(false);
  const [transaction, setTransaction] = useState<Transaction | null>(null);
  const [operationId, setOperationId] = useState(() => crypto.randomUUID());
  const titleRef = useRef<HTMLHeadingElement>(null);
  const confirmLock = useRef(false);
  const unread = snapshot.notifications.filter((item) => !item.read).length;
  const afterBalance = Math.max(0, snapshot.balance.available - amount);
  useEffect(() => { titleRef.current?.focus({ preventScroll: true }); }, [step]);
  const recipientStatus = useMemo(() => { if (!keyValue.trim()) return null; const type = detectPixKeyType(keyValue); if (!type) return { kind: 'invalid' as const, message: 'A chave não tem um formato Pix válido.' }; const found = findPixRecipient(keyValue, demoPixRecipients); if (!found) return { kind: 'not-found' as const, message: 'Não encontramos um destinatário para esta chave.' }; return { kind: 'found' as const, recipient: found }; }, [keyValue]);
  const chooseRecipient = (event: FormEvent) => { event.preventDefault(); if (!recipientStatus || recipientStatus.kind !== 'found') { setError(recipientStatus?.message ?? 'Informe uma chave Pix.'); requestAnimationFrame(() => document.getElementById('pix-key')?.focus()); return; } setRecipient(recipientStatus.recipient); setError(''); setStep('amount'); };
  const chooseAmount = (event: FormEvent) => { event.preventDefault(); const validation = validatePixAmount(amount, snapshot); if (validation && !validation.ok) { setError(validation.message); requestAnimationFrame(() => document.getElementById('pix-amount')?.focus()); return; } setError(''); setStep('review'); };
  const confirmPix = () => { if (!recipient || processing || confirmLock.current) return; confirmLock.current = true; setProcessing(true); const result = snapshot.submitPix({ operationId, recipient, amount, createdAt: new Date().toISOString() }); if (!result.ok) { setError(result.message); setProcessing(false); confirmLock.current = false; return; } setTransaction(result.transaction); setStep('reaction'); const duration = window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 0 : 760; window.setTimeout(() => { setStep('receipt'); setProcessing(false); }, duration); };
  const startAnother = () => { setKeyValue(''); setRecipient(null); setAmount(0); setAmountText(''); setError(''); setTransaction(null); setOperationId(crypto.randomUUID()); confirmLock.current = false; setStep('recipient'); };
  const datePreview = formatDateTime(new Date().toISOString());
  return <div className="pix-page route-stage"><a className="skip-link" href="#pix-content">Pular para o Pix</a><AppHeader unreadCount={unread} /><main className="pix-shell" id="pix-content"><header className="pix-header"><Link to="/dashboard" className="back-link"><ArrowLeft aria-hidden="true" /> Dashboard</Link><div><p className="kicker">PIX / MONEY IN MOTION</p><h1 ref={titleRef} tabIndex={-1}>{step === 'receipt' ? 'Comprovante' : 'Mover dinheiro.'}</h1></div><PixFlow active={stepIndex[step]} /></header>
  {step === 'recipient' && <section className="pix-stage pix-stage--recipient" aria-labelledby="recipient-title"><div className="pix-stage__context"><span>01</span><p>SOURCE → DESTINATION</p><h2 id="recipient-title">Para quem<br />você envia?</h2><p>Informe uma chave. O destinatário precisa ser reconhecido antes de qualquer valor.</p></div><form className="pix-form" onSubmit={chooseRecipient} noValidate><label htmlFor="pix-key">Chave Pix</label><div className="pix-key-input"><Search aria-hidden="true" /><input id="pix-key" value={keyValue} onChange={(event) => { setKeyValue(event.target.value); setError(''); }} placeholder="CPF, telefone, e-mail ou chave aleatória" autoComplete="off" aria-invalid={Boolean(error)} aria-describedby="pix-key-help pix-error" /></div><p id="pix-key-help" className="pix-help">Exemplo: <button type="button" onClick={() => setKeyValue(pixRecipientExamples.email)}>{pixRecipientExamples.email}</button></p>{recipientStatus?.kind === 'found' && <div className="recipient-result" aria-live="polite"><span><Check aria-hidden="true" /></span><div><strong>{recipientStatus.recipient.name}</strong><small>{recipientStatus.recipient.maskedKey}</small><small>{recipientStatus.recipient.institution} · {recipientStatus.recipient.taxIdSuffix}</small></div></div>}{recipientStatus && recipientStatus.kind !== 'found' && <p className="field__error" aria-live="polite">{recipientStatus.message}</p>}{error && <p id="pix-error" className="field__error" role="alert">{error}</p>}<button className="pix-primary" type="submit">Continuar <ArrowRight aria-hidden="true" /></button></form></section>}
  {step === 'amount' && recipient && <section className="pix-stage pix-stage--amount" aria-labelledby="amount-title"><div className="pix-stage__context"><span>02</span><p>CHOICE SPLIT</p><h2 id="amount-title">Quanto vai<br />se mover?</h2><div className="recipient-inline"><strong>{recipient.name}</strong><span>{recipient.maskedKey}</span><button type="button" onClick={() => setStep('recipient')}><Edit3 aria-hidden="true" /> Alterar</button></div></div><form className="amount-form" onSubmit={chooseAmount} noValidate><label htmlFor="pix-amount">Valor do Pix</label><div className="amount-input"><span>R$</span><input id="pix-amount" inputMode="numeric" value={amountText} onChange={(event) => { const next = parseMoneyInput(event.target.value); setAmount(next); setAmountText(next ? next.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : ''); setError(''); }} placeholder="0,00" aria-invalid={Boolean(error)} aria-describedby="amount-error" autoFocus /></div><div className="choice-split" aria-live="polite"><div><span>SALDO ATUAL</span><strong>{formatMoney(snapshot.balance.available)}</strong></div><div className="choice-split__send"><span>ENVIAR</span><strong>− {formatMoney(amount)}</strong></div><div><span>MANTER DISPONÍVEL</span><strong>{formatMoney(afterBalance)}</strong></div></div><p className="pix-limit">Limite Pix diário: {formatMoney(snapshot.account.pixDailyLimit)}</p>{error && <p id="amount-error" className="field__error" role="alert">{error}</p>}<button className="pix-primary" type="submit">Revisar Pix <ArrowRight aria-hidden="true" /></button></form></section>}
  {step === 'review' && recipient && <section className="pix-stage pix-stage--review" aria-labelledby="review-title"><div className="pix-stage__context"><span>03</span><p>DECISION</p><h2 id="review-title">Revise antes<br />de confirmar.</h2><p>O saldo só será alterado depois da sua confirmação.</p></div><div className="pix-review"><p className="pix-review__amount">{formatMoney(amount)}</p><dl><div><dt>Origem</dt><dd>{snapshot.account.institution}<small>Ag. {snapshot.account.branch} · Conta {snapshot.account.number}</small></dd></div><div><dt>Destinatário</dt><dd>{recipient.name}<small>{recipient.taxIdSuffix}</small></dd></div><div><dt>Chave</dt><dd>{recipient.maskedKey}</dd></div><div><dt>Instituição</dt><dd>{recipient.institution}</dd></div><div><dt>Data</dt><dd>{datePreview.date}, agora</dd></div><div><dt>Saldo após o Pix</dt><dd>{formatMoney(afterBalance)}</dd></div></dl>{error && <p className="field__error" role="alert">{error}</p>}<div className="pix-review__actions"><button type="button" onClick={() => setStep('amount')} disabled={processing}>Voltar e editar</button><button className="pix-confirm" type="button" onClick={confirmPix} disabled={processing}>{processing ? 'Confirmando…' : `Confirmar Pix de ${formatMoney(amount)}`} <ArrowRight aria-hidden="true" /></button></div></div></section>}
  {step === 'reaction' && transaction && <section className="balance-reaction" aria-labelledby="reaction-title"><div className="balance-reaction__source"><span>SALDO ANTERIOR</span><strong>{formatMoney(snapshot.balance.available + transaction.amount)}</strong></div><div className="balance-reaction__transfer"><span aria-hidden="true" /><strong>− {formatMoney(transaction.amount)}</strong><small>para {transaction.recipient}</small></div><div className="balance-reaction__result"><span>NOVO SALDO</span><strong id="reaction-title" tabIndex={-1}>{formatMoney(snapshot.balance.available)}</strong></div><p className="sr-status" role="status">Pix concluído. Seu novo saldo é {formatMoney(snapshot.balance.available)}.</p></section>}
  {step === 'receipt' && transaction && <section className="receipt-stage"><Receipt transaction={transaction} /><div className="receipt-next"><Link to="/dashboard">Voltar ao Dashboard <ArrowRight aria-hidden="true" /></Link><button type="button" onClick={startAnother}>Fazer outro Pix</button></div></section>}</main></div>;
}
